In [1]:
import numpy as np

In [3]:
scores = np.array([
    [85, 90, 78],
    [92, 88, 95],
    [70, 75, 80],
    [60, 65, 58]
])
scores

array([[85, 90, 78],
       [92, 88, 95],
       [70, 75, 80],
       [60, 65, 58]])

In [4]:
# 전체 데이터 구조 확인
scores.shape

(4, 3)

In [8]:
# 행 기준으로 평균 계산 (axis=1은 "행 기준" / 한 학생의 점수들을 묶어서 평균 구하기)
student_avg = scores.mean(axis=1)
student_avg

array([84.33333333, 91.66666667, 75.        , 61.        ])

In [12]:
# 과목별 평균 (axis=0은 "열 기준")
subject_avg = scores.mean(axis=0)
subject_avg

array([76.75, 79.5 , 77.75])

In [11]:
# 평균이 80점 이상인 학생만
passed = student_avg >= 80
passed_students = scores[passed]
passed_students

array([[85, 90, 78],
       [92, 88, 95]])

In [13]:
# 특정 과목에서 90점 이상 받은 점수만 보기
high_scores = scores[scores >= 90]
high_scores

array([90, 92, 95])

In [14]:
# 점수 보정 (ex: 전체 점수에 5점을 가산하되, 100점은 넘지 않게)
adjusted = scores + 5
adjusted = np.clip(adjusted, 0, 100)
adjusted

array([[ 90,  95,  83],
       [ 97,  93, 100],
       [ 75,  80,  85],
       [ 65,  70,  63]])

In [15]:
# 데이터 타입 변환
raw = np.array(["80", "90", "75"])
nums = raw.astype(int)
nums

array([80, 90, 75])